#!/bin/bash

DZEN_OPTS=" -bg darkslategray -fg white -xs 1 -ta l -fn 6x12 -p -u "
IMAGE="/tmp/screenshot-$(date +'%F.%T').png"
echo "Screenshot -> Imgur: Click a window or drag a selection." | dzen2 $DZEN_OPTS &
PID=$!
scrot -s $IMAGE

if [ $? -eq 0 ] ; then
  kill $PID
  echo "Uploading..." | dzen2 $DZEN_OPTS &
  PID=$!

  url="$(imgur.sh $IMAGE)"
  x-www-browser "$url" 
  echo "!$url|width=400px!"
fi

kill $PID
