#!/bin/bash
#
# Borrowed from: http://sirupsen.com/a-simple-imgur-bash-screenshot-utility/
#
# Requires: curl, dzen2, scrot, firefox
# Suggested: xsel, cli-board
#
# Prompts for a screenshot, which can be window or selection.  Uploads screenshot to imgur.  
# Returns GitHub markdown for showing image

function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "<original_image>(.)*</original_image>" | grep -E -o "http://i.imgur.com/[^<]*"
}

DZEN_OPTS=" -bg darkslategray -fg white -xs 1 -ta l -fn 6x12 -p -u "


echo "Screenshot -> Imgur: Click a window or drag a selection." | dzen2 $DZEN_OPTS &
PID=$!

if $(scrot -s "/tmp/screenshot.png") ; then
  kill $PID

  echo "Uploading..." | dzen2 $DZEN_OPTS &
  PID=$!

  url=$(uploadImage "/tmp/screenshot.png")
  firefox $url
  rm "/tmp/screenshot.png"
  kill $PID
  echo "![screenshot]($url)" 
else
  kill $PID
fi
