#!/bin/bash
#
# By Sirupsen @ http://sirupsen.dk
#
# Description: Very simple script to make you
# select a region of your screen, which will be captured, and
# then uploaded. The URL will then be injected into your clipboard.
#
# Dependencies:
#
# Imgur Bash Upload Script (http://imgur.com/tools/imgurbash.sh)
# Comment: Must be in path (see below) with the name "imgur" (not imgur.sh)
#
# Scrot
# Comment: Scrot is what takes the actual screenshot.
#
# Xclip
# Comment: Xclip is what makes the script able to inject the direct url
# into your clipboard.
#
# libnotify*
# Comment: Will notify you whenever the direct URL is in the clipboard
#
# Installation:
#
# Move the file to a local bin. And put the path of this bin, into
# your path. (See: www.troubleshooters.com/linux/prepostpath.htm)
#
# From then on, you can either activate it via your terminal, or via
# your window manager or similar, so you can bind it to a keycombination.
#

# Modified as follows.  xsel instead of xclip.  No more libnotify.  Dzen for prompt.  
# Result is opened in firefox.
# GitHub markdown link to image is returned.

function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "<original_image>(.)*</original_image>" | grep -E -o "http://i.imgur.com/[^<]*"
}

DZEN_OPTS=" -bg darkslategray -fg white -xs 1 -ta l -fn 6x12 -p -u "


echo "Screenshot -> Imgur: Click a window or drag a selection." | dzen2 $DZEN_OPTS &
PID=$!

scrot -s "/tmp/screenshot.png" 
kill $PID

echo "Uploading..." | dzen2 $DZEN_OPTS &
PID=$!

url=$(uploadImage "/tmp/screenshot.png")
firefox $url
rm "/tmp/screenshot.png"
kill $PID
echo "![screenshot]($url)" 
