Metrics/LineLength:
  Enabled: true
  Max: 160

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
