Lint/RedundantCopDisableDirective:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

# to override, define a .rubocop.override.yml in your project.  gitignore it.  call it explicitly with rubocop wrapper
# inherit_from:
#   - ./.rubocop.yml
#   - ../../.rubocop.yml
