#!/bin/sh

# some envs want `bundle exec`.  others want `docker/run`.  tell vim to use
# this script and let the env decide how to run tests for us.

export RUBYOPT="$PRYOPT"

if [[ -f "docker/run" ]] ; then
  # docker/run RUBYOPT="'$RUBYOPT'" bundle exec $@
  docker/run BUNDLE_GEMFILE="'$BUNDLE_GEMFILE'" bundle exec $@
else
  bundle exec $@
fi
