#!/bin/bash

set_color() {
 dkcmd set border width=1 outer_width=0 colour focus="$1" # outer_focus="#000000"
 sleep 0.04
}

# set_color \#ddddee
set_color \#ccccdd
set_color \#bbbbaa
set_color \#aaaabb
set_color \#999999
set_color \#888888
set_color \#777777

# dkcmd set border width=1 outer_width=1 unfocus="#ff0000" focus="#00ff00"
