#!/bin/bash

set_color() {
 dkcmd set border colour outer_focus="$1"
 sleep 0.04
}


dkcmd set border color focus="#ccccdd"
# set_color \#eeeeff
set_color \#ccccdd
dkcmd set border color focus="#222222"
# set_color \#ddddee
set_color \#ccccdd
set_color \#bbbbaa
set_color \#aaaabb
set_color \#9999aa
set_color \#888888
