#!/usr/bin/bash

current_desktop() { wmctrl -d | awk '/\*/ { print $1 }'; }
color_for_desktop() {
    case "$1" in
        0) c="#ff0000" ;;
        1) c="#00ff00" ;;
        2) c="#0000ff" ;;
        3) c="#ff00ff" ;;
        4) c="#00ffff" ;;
        5) c="#ffff00" ;;
        6) c="#ffffff" ;;
        7) c="#aaccee" ;;
        8) c="#eeccaa" ;;
        9) c="#cceeaa" ;;
    esac
    echo "$c"
}

dk_set_border_color() {
    dkcmd set border color outer_focus="$1"
}


refresh_border_color() {
    color="$(color_for_desktop $(current_desktop))"
    dk_set_border_color $color
}

dkcmd status type=bar |
    grep '^W'  --line-buffered |
    while read -r line ; do
        refresh_border_color
        sleep 0.1
    done
