#!/bin/bash

# I3LOCK="i3lock -f -o -s 15 -r 30 -e"
I3LOCK="i3lock  -e"
xautolock -time 10 \
  -locker "$I3LOCK" \
  -notifier "xset dpms force off" \
  -notify 20 \
  -detectsleep \
  -corners -000 # don't sleep if mouse is in top left corner
