#!/bin/bash -ue

# add this to ~/.local/share/applications
# [Desktop Entry]
# Terminal=false
# Type=Application
# Exec=ssh-handler %U

dest=${1#ssh://}

ssh_opts="-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
x-terminal-emulator -bg '#223' -e "vpnup.sh ; ssh $ssh_opts ${dest}" &
