#!/bin/bash -ue

# add this to ~/.local/share/applications
# [Desktop Entry]
# Terminal=false
# Type=Application
# Exec=ssh-handler %U

# in firefox's about:config set network.protocol-handler.expose.ssh to false

dest=${1#ssh://}

ssh_opts="-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
xterm -bg '#223' -e "vpnup.sh ; ssh $ssh_opts ${dest}"
