# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    ci: '!script -q /tmp/gh-script -c "gh pr checks" | grep "0 pending" || (echo -n . ; sleep 30 ; gh ci)'
